name: Bug report
description: You've got a problem with this module, open a new issue
assignees: nenes25
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        # Please provide the maximum informations you can to help us reproduce the bug. 
        
        Thank you for using the module and reporting an issue In order to allow us to help you, please fill the following fields
  - type: checkboxes
    attributes:
      label: Check if your feature request exists
      options:
        - label: I confirm that i've search that my feature request does not already exists
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
      attributes:
        label: Additional context
        placeholder: Add any other context or screenshots about the feature request here.