name: Feature request
description:  You want a new feature for this project
title: "[enhancement]: "
labels: ["enhancement"]
assignees:
  - nenes25
body:
  - type: markdown
    attributes:
      value: |
        Please provide the maximum informations you can to help us reproduce the bug.
        Thank you for using the module and reporting an issue In order to allow us to help you, please fill the following fields
  - type: checkboxes
    id: exists
    attributes:
      label: Check if your feature request exists
      description: I confirm that i've search that my feature request does not already exists
      options:
        - label: My feature request does not already exists
          required: true
  - type: textarea
    id: related
    attributes:
      label: Is your feature request related to a problem?
      description: Is your feature request related to a problem?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additionnal
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
